### PR TITLE
Update Steam_description_SPA.txt

### PR DESCRIPTION
**Pull request by FerchuDev**

### CODE REVIEW

**Comment by cybrxkhan** [comment]
Thanks!

**Comment by FerchuDev** [comment]
@cybrxkhan could you update the mod description on Steam in Spanish?

**Comment by cybrxkhan** [comment]
> @cybrxkhan could you update the mod description on Steam in Spanish?
> 

I actually won't be able to use my computer for a day or two since I'm busy with IRL stuff atm 😭 

Thanks for reminding me though, I'll try to remember to do that once I can get on my computer again.

**Review by cybrxkhan — APPROVED** [review]

**Comment by cybrxkhan** [comment]
@FerchuDev 
I just figured out how to update the steam workshop description on my phone, so I have changed the Spanish version of it accordingly. Hopefully that works and thanks!

**Comment by FerchuDev** [comment]
@cybrxkhan 
That's perfect, thank you very much!

**Comment by FerchuDev** [comment]
@cybrxkhan 
I noticed that I uploaded an image incorrectly, so I created this pull request to fix it. Sorry for the inconvenience.
https://github.com/cybrxkhan/RICE-for-CK3/pull/161

**Comment by cybrxkhan** [comment]
> @cybrxkhan 
> I noticed that I uploaded an image incorrectly, so I created this pull request to fix it. Sorry for the inconvenience.
> https://github.com/cybrxkhan/RICE-for-CK3/pull/161
> 

Ok just updated it, thanks!

**Pull request merged**
